/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistem;
    import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class DestinasiForm extends javax.swing.JFrame {
    
    dbCRUD crud;
    String JudulKolom[] = {"ID Destinasi", "Nama Destinasi", "Lokasi", "Kategori", "Deskripsi", "Harga Tiket"};
    int lebarkolom[] = {50, 150, 200, 150, 100, 150};
    String sql = "SELECT * FROM destinasi";

    /**
     * Creates new form PelangganForm
     */
    public DestinasiForm() {
        initComponents();
        crud = new dbCRUD();
        loadData();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
        populateFields();
        jButton7 = new javax.swing.JButton();
        jButton7.setText("CETAK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
    }
});

    }
});

    }
    
    public void loadData() {
        crud.setJudulTable(jTable1, JudulKolom);
        crud.setLebarKolom(jTable1, lebarkolom);
        crud.setTampilTabel(jTable1, sql, JudulKolom);
    }
    
    private void clearFields() {
        jTextIdDestinasi.setText("");
        jTextNamaDestinasi.setText("");
        jTextLokasi.setText("");
        jTextKategori.setText("");
        jTextDeskripsi.setText("");
        jTextHargaTiket.setText("");
}

   private void populateFields() {
    int selectedRow = jTable1.getSelectedRow();
    int columnCount = jTable1.getColumnCount(); // Jumlah kolom di tabel

    if (selectedRow != -1) { // Pastikan ada baris yang dipilih
        if (columnCount >= 6) { // Pastikan jumlah kolom cukup
            jTextIdDestinasi.setText(jTable1.getValueAt(selectedRow, 0).toString());
            jTextNamaDestinasi.setText(jTable1.getValueAt(selectedRow, 1).toString());
            jTextLokasi.setText(jTable1.getValueAt(selectedRow, 2).toString());
            jTextKategori.setText(jTable1.getValueAt(selectedRow, 3).toString());
            jTextDeskripsi.setText(jTable1.getValueAt(selectedRow, 4).toString());
            jTextHargaTiket.setText(jTable1.getValueAt(selectedRow, 5).toString());
        } else {
            // Tampilkan pesan error jika jumlah kolom tidak cukup
            JOptionPane.showMessageDialog(this, "Jumlah kolom tabel tidak sesuai. Harus minimal 6 kolom.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Tampilkan pesan error jika tidak ada baris yang dipilih
        JOptionPane.showMessageDialog(this, "Pilih baris di tabel terlebih dahulu.", 
                                      "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextIdDestinasi = new javax.swing.JTextField();
        jTextNamaDestinasi = new javax.swing.JTextField();
        jTextLokasi = new javax.swing.JTextField();
        jTextDeskripsi = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextKategori = new javax.swing.JTextField();
        jTextHargaTiket = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Destinasi");

        jLabel2.setText("Nama Destinasi");

        jLabel3.setText("Lokasi");

        jLabel4.setText("Deskripsi");

        jTextIdDestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdDestinasiActionPerformed(evt);
            }
        });

        jTextLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLokasiActionPerformed(evt);
            }
        });

        jTextDeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDeskripsiActionPerformed(evt);
            }
        });

        jButton4.setText("SIMPAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("UBAH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("HAPUS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton7.setText("CETAK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setText("Kategori");

        jLabel6.setText("Harga Tiket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextIdDestinasi, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(jTextNamaDestinasi)
                                    .addComponent(jTextLokasi)
                                    .addComponent(jTextHargaTiket)
                                    .addComponent(jTextDeskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(jTextKategori)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextIdDestinasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNamaDestinasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextHargaTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            String id = jTextIdDestinasi.getText();

            crud.HapusDinamis("destinasi", "id", id);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            loadData();
            clearFields();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            String id = jTextIdDestinasi.getText();
            String Nama = jTextNamaDestinasi.getText();
            String Lokasi = jTextLokasi.getText();
            String Kategori = jTextKategori.getText();
            String Deskripsi = jTextDeskripsi.getText();
            String Harga = jTextHargaTiket.getText();

            String[] fields = {"id", "Nama", "Lokasi", "Kategori", "Deskripsi", "Harga"};
            String[] values = {id, Nama, Lokasi, Kategori, Deskripsi, Harga};

            crud.SimpanDinamis("destinasi", fields, values);
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            loadData();
            clearFields();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String id = jTextIdDestinasi.getText();
            String Nama = jTextNamaDestinasi.getText();
            String Lokasi = jTextLokasi.getText();
            String Kategori = jTextKategori.getText();
            String Deskripsi = jTextDeskripsi.getText();
            String Harga = jTextHargaTiket.getText();


            String[] fields = {"Nama", "Lokasi", "Kategori", "Deskripsi", "Harga"};
            String[] values = {Nama, Lokasi, Kategori, Deskripsi, Harga};

            crud.UbahDinamis("destinasi", "id", id, fields, values);
            JOptionPane.showMessageDialog(null, "Berhasil diubah");
            loadData();
            clearFields();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextIdDestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdDestinasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdDestinasiActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
        boolean printSuccess = jTable1.print(javax.swing.JTable.PrintMode.FIT_WIDTH, 
            new java.text.MessageFormat("DESTINASI WISATA"), 
            new java.text.MessageFormat("Halaman {0}"));
        if (printSuccess) {
            JOptionPane.showMessageDialog(null, "Data berhasil dicetak");
        } else {
            JOptionPane.showMessageDialog(null, "Cetak dibatalkan");
        }
    } catch (java.awt.print.PrinterException e) {
        JOptionPane.showMessageDialog(null, "Gagal mencetak: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDeskripsiActionPerformed

    private void jTextLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLokasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DestinasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DestinasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DestinasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DestinasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(DestinasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(DestinasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(DestinasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(DestinasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                
                }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DestinasiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDeskripsi;
    private javax.swing.JTextField jTextHargaTiket;
    private javax.swing.JTextField jTextIdDestinasi;
    private javax.swing.JTextField jTextKategori;
    private javax.swing.JTextField jTextLokasi;
    private javax.swing.JTextField jTextNamaDestinasi;
    // End of variables declaration//GEN-END:variables
}
