package Sistem;


import Sistem.HOME;
import Sistem.dbCRUD;
    import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class ReservasiForm extends javax.swing.JFrame {
    
    dbCRUD crud;
    String JudulKolom[] = {"ID Reservasi", "ID Pengunjung", "ID Destinasi","Tangal Reservasi", "Jumlah Tiket", "Total Harga"};
    int lebarkolom[] = {50, 150, 200, 150, 100, 300};
    String sql = "SELECT * FROM reservasi";

    /**
     * Creates new form ReservasiForm
     */
    public ReservasiForm() {
        initComponents();
        crud = new dbCRUD();
        loadData();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
        populateFields();
        jButton4 = new javax.swing.JButton();
        jButton4.setText("CETAK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
    }
});

    }
});
    }
    
    public void loadData() {
        crud.setJudulTable(jTable1, JudulKolom);
        crud.setLebarKolom(jTable1, lebarkolom);
        crud.setTampilTabel(jTable1, sql, JudulKolom);
    }
    
    private void clearFields() {
        jTextIdDestinasi.setText("");
        jTextIdPengunjung.setText("");
        jTextIdReservasi.setText("");
        jTextTanggalReservasi.setText("");
        jTextJumlahTiket.setText("");
        jTextTotal.setText("");
}

   private void populateFields() {
    int selectedRow = jTable1.getSelectedRow();
    int columnCount = jTable1.getColumnCount(); // Jumlah kolom di tabel

    if (selectedRow != -1) { // Pastikan ada baris yang dipilih
        if (columnCount >= 6) { // Pastikan jumlah kolom cukup (sesuai kolom yang digunakan)
            // Isi field dengan data dari tabel
            jTextIdReservasi.setText(jTable1.getValueAt(selectedRow, 0).toString());
            jTextIdPengunjung.setText(jTable1.getValueAt(selectedRow, 1).toString());
            jTextIdDestinasi.setText(jTable1.getValueAt(selectedRow, 2).toString());
            jTextTanggalReservasi.setText(jTable1.getValueAt(selectedRow, 3).toString());
            jTextJumlahTiket.setText(jTable1.getValueAt(selectedRow, 4).toString());
            jTextTotal.setText(jTable1.getValueAt(selectedRow, 5).toString());
        } else {
            // Tampilkan pesan error jika jumlah kolom tidak cukup
            JOptionPane.showMessageDialog(this, 
                "Jumlah kolom tabel tidak sesuai. Harus minimal 5 kolom.", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Tampilkan pesan error jika tidak ada baris yang dipilih
        JOptionPane.showMessageDialog(this, 
            "Pilih baris di tabel terlebih dahulu.", 
            "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextIdReservasi = new javax.swing.JTextField();
        jTextIdPengunjung = new javax.swing.JTextField();
        jTextIdDestinasi = new javax.swing.JTextField();
        jTextTanggalReservasi = new javax.swing.JTextField();
        jTextJumlahTiket = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Reservasi");

        jLabel2.setText("ID Pengunjung");

        jLabel3.setText("ID Destinasi");

        jLabel4.setText("Tanggal Reservasi");

        jLabel5.setText("Jumlah Tiket");

        jLabel6.setText("Total Harga");

        jTextIdDestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdDestinasiActionPerformed(evt);
            }
        });

        jTextTotal.setText("Rp.");

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("UBAH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CETAK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("KEMBALI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextIdReservasi)
                                    .addComponent(jTextIdPengunjung)
                                    .addComponent(jTextIdDestinasi)
                                    .addComponent(jTextTanggalReservasi)
                                    .addComponent(jTextJumlahTiket)
                                    .addComponent(jTextTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButton3)
                                .addGap(33, 33, 33)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton4)
                        .addGap(44, 44, 44)
                        .addComponent(jButton5)))
                .addGap(127, 127, 127)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextIdReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextIdPengunjung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextIdDestinasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextTanggalReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextJumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIdDestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdDestinasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdDestinasiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String IdR = jTextIdReservasi.getText();
            String IdP = jTextIdPengunjung.getText();
            String IdD = jTextIdDestinasi.getText();
            String Tanggal = jTextTanggalReservasi.getText();
            String Jumlah = jTextJumlahTiket.getText();
            String Total = jTextTotal.getText();

            String[] fields = {"id_reservasi", "id_pengunjung", "id_destinasi", "tanggal_reservasi", "jumlah_tiket", "total_harga"};
            String[] values = {IdR, IdP, IdD, Tanggal, Jumlah, Total};

            crud.SimpanDinamis("reservasi", fields, values);
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            loadData();
            clearFields();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
           String IdR = jTextIdReservasi.getText();
            String IdP = jTextIdPengunjung.getText();
            String IdD = jTextIdDestinasi.getText();
            String Tanggal = jTextTanggalReservasi.getText();
            String Jumlah = jTextJumlahTiket.getText();
            String Total = jTextTotal.getText();

            String[] fields = {"id_pengunjung", "id_destinasi", "tanggal_reservasi", "jumlah_tiket", "total_harga"};
            String[] values = {IdP, IdD, Tanggal, Jumlah, Total};

            crud.UbahDinamis("reservasi", "id_reservasi", IdR, fields, values);
            JOptionPane.showMessageDialog(null, "Berhasil diubah");
            loadData();
            clearFields();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
            String IdR = jTextIdReservasi.getText();

            crud.HapusDinamis("reservasi", "id_reservasi", IdR);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            loadData();
            clearFields();
        } catch (Exception e) {
            System.err.println("Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
        try {
        boolean printSuccess = jTable1.print(javax.swing.JTable.PrintMode.FIT_WIDTH, 
            new java.text.MessageFormat("DAFTAR RESERVASI"), 
            new java.text.MessageFormat("Halaman {0}"));
        if (printSuccess) {
            JOptionPane.showMessageDialog(null, "Data berhasil dicetak");
        } else {
            JOptionPane.showMessageDialog(null, "Cetak dibatalkan");
        }
    } catch (java.awt.print.PrinterException e) {
        JOptionPane.showMessageDialog(null, "Gagal mencetak: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        HOME home = new HOME(); // Ganti 'HomeForm' dengan nama class form utama Anda
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(ReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(ReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(ReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(ReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservasiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservasiForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextIdDestinasi;
    private javax.swing.JTextField jTextIdPengunjung;
    private javax.swing.JTextField jTextIdReservasi;
    private javax.swing.JTextField jTextJumlahTiket;
    private javax.swing.JTextField jTextTanggalReservasi;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
}
